# Generated by Django 3.1.7 on 2021-05-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectlocation', models.CharField(choices=[('viajayawada', 'vijawada'), ('hyderabad', 'hyderabad')], default='select location', max_length=20)),
                ('selectdepartment', models.CharField(choices=[('cardio', 'cardio'), ('neuro', 'neuro'), ('gastro', 'gastro')], default='selectdepartment', max_length=30)),
                ('patientname', models.CharField(max_length=30)),
                ('patientmobile', models.CharField(max_length=30)),
                ('patientEmail', models.CharField(max_length=30)),
                ('doctor', models.CharField(choices=[('k.jayasurya', 'k.jayasurya'), ('b.padmanabhasimha', 'b.padmanabhasimha')], default='doctor', max_length=40)),
            ],
        ),
    ]
