# Generated by Django 3.1.7 on 2021-05-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_appointment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='timestamp',
        ),
    ]
