# Generated by Django 3.1.7 on 2021-05-05 13:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_appointment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='datetime',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 5, 5, 13, 13, 39, 896618, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
