# Generated by Django 3.1.7 on 2021-05-05 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_appointment_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=40)),
                ('symptoms', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAdvice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remedy', models.CharField(max_length=40)),
                ('patientname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.prescription')),
            ],
        ),
    ]
