# Generated by Django 3.1.7 on 2021-05-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_appointment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phonenumber', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
    ]
