# Generated by Django 3.1.7 on 2021-05-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_ambulance'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='previoushealthrecord',
            field=models.CharField(default='asthama', max_length=60),
        ),
    ]
