# Generated by Django 3.1.7 on 2021-05-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_appointment_previoushealthrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='previousmedication',
            field=models.CharField(default='diabetic', max_length=60),
        ),
    ]
