# Generated by Django 3.1.7 on 2021-05-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_appointment_previousmedication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctorregister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('specialilization', models.CharField(max_length=40)),
                ('maxappointments', models.IntegerField(max_length=40)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
