# Generated by Django 3.1.7 on 2021-05-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_doctorregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregister',
            name='email',
            field=models.CharField(default='abcd@gmail.com', max_length=40),
        ),
        migrations.AddField(
            model_name='doctorregister',
            name='phone',
            field=models.CharField(default='abcd@gmail.com', max_length=40),
        ),
    ]
