# Generated by Django 3.1.7 on 2021-05-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20210518_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorregister',
            old_name='specialilization',
            new_name='specialization',
        ),
        migrations.AlterField(
            model_name='doctorregister',
            name='phone',
            field=models.CharField(default='12345678', max_length=40),
        ),
    ]
