# Generated by Django 3.1.7 on 2021-05-18 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20210518_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='datetime',
            new_name='date',
        ),
    ]
