# Generated by Django 3.1.7 on 2021-05-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='d',
            new_name='datetime',
        ),
    ]
