# Generated by Django 3.1.7 on 2021-05-18 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_auto_20210518_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='doctorname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.doctorregister', unique=True),
        ),
    ]
