# Generated by Django 3.1.7 on 2021-05-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20210518_2043'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('doctorname', 'filled')},
        ),
    ]
