# Generated by Django 3.1.7 on 2021-05-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_auto_20210518_2058'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='status',
            unique_together=set(),
        ),
    ]
