# Generated by Django 3.1.7 on 2021-05-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_auto_20210518_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='delay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=40)),
                ('patientstatus', models.CharField(default='waiting', max_length=40)),
            ],
        ),
    ]
