# Generated by Django 3.1.7 on 2021-05-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_auto_20210519_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='images',
            field=models.ImageField(upload_to='cartimg/'),
        ),
    ]
