# Generated by Django 3.1.7 on 2021-05-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_auto_20210519_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=40)),
            ],
        ),
    ]
