# Generated by Django 3.1.7 on 2021-05-19 04:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_auto_20210519_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='delay',
            name='datetime',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='showcart',
            name='price',
            field=models.IntegerField(),
        ),
    ]
